/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AboutPegasusRouteImport } from './routes/about-pegasus'
import { Route as SystemsRouteRouteImport } from './routes/systems/route'
import { Route as CareerRouteRouteImport } from './routes/career/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SystemsEducationRouteImport } from './routes/systems/education'
import { Route as SystemsBplaRouteImport } from './routes/systems/bpla'
import { Route as SystemsBpakRouteImport } from './routes/systems/bpak'
import { Route as CareerCareerIdRouteRouteImport } from './routes/career/$careerId/route'

const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutPegasusRoute = AboutPegasusRouteImport.update({
  id: '/about-pegasus',
  path: '/about-pegasus',
  getParentRoute: () => rootRouteImport,
} as any)
const SystemsRouteRoute = SystemsRouteRouteImport.update({
  id: '/systems',
  path: '/systems',
  getParentRoute: () => rootRouteImport,
} as any)
const CareerRouteRoute = CareerRouteRouteImport.update({
  id: '/career',
  path: '/career',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SystemsEducationRoute = SystemsEducationRouteImport.update({
  id: '/education',
  path: '/education',
  getParentRoute: () => SystemsRouteRoute,
} as any)
const SystemsBplaRoute = SystemsBplaRouteImport.update({
  id: '/bpla',
  path: '/bpla',
  getParentRoute: () => SystemsRouteRoute,
} as any)
const SystemsBpakRoute = SystemsBpakRouteImport.update({
  id: '/bpak',
  path: '/bpak',
  getParentRoute: () => SystemsRouteRoute,
} as any)
const CareerCareerIdRouteRoute = CareerCareerIdRouteRouteImport.update({
  id: '/$careerId',
  path: '/$careerId',
  getParentRoute: () => CareerRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/career': typeof CareerRouteRouteWithChildren
  '/systems': typeof SystemsRouteRouteWithChildren
  '/about-pegasus': typeof AboutPegasusRoute
  '/blog': typeof BlogRoute
  '/contact': typeof ContactRoute
  '/career/$careerId': typeof CareerCareerIdRouteRoute
  '/systems/bpak': typeof SystemsBpakRoute
  '/systems/bpla': typeof SystemsBplaRoute
  '/systems/education': typeof SystemsEducationRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/career': typeof CareerRouteRouteWithChildren
  '/systems': typeof SystemsRouteRouteWithChildren
  '/about-pegasus': typeof AboutPegasusRoute
  '/blog': typeof BlogRoute
  '/contact': typeof ContactRoute
  '/career/$careerId': typeof CareerCareerIdRouteRoute
  '/systems/bpak': typeof SystemsBpakRoute
  '/systems/bpla': typeof SystemsBplaRoute
  '/systems/education': typeof SystemsEducationRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/career': typeof CareerRouteRouteWithChildren
  '/systems': typeof SystemsRouteRouteWithChildren
  '/about-pegasus': typeof AboutPegasusRoute
  '/blog': typeof BlogRoute
  '/contact': typeof ContactRoute
  '/career/$careerId': typeof CareerCareerIdRouteRoute
  '/systems/bpak': typeof SystemsBpakRoute
  '/systems/bpla': typeof SystemsBplaRoute
  '/systems/education': typeof SystemsEducationRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/career'
    | '/systems'
    | '/about-pegasus'
    | '/blog'
    | '/contact'
    | '/career/$careerId'
    | '/systems/bpak'
    | '/systems/bpla'
    | '/systems/education'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/career'
    | '/systems'
    | '/about-pegasus'
    | '/blog'
    | '/contact'
    | '/career/$careerId'
    | '/systems/bpak'
    | '/systems/bpla'
    | '/systems/education'
  id:
    | '__root__'
    | '/'
    | '/career'
    | '/systems'
    | '/about-pegasus'
    | '/blog'
    | '/contact'
    | '/career/$careerId'
    | '/systems/bpak'
    | '/systems/bpla'
    | '/systems/education'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CareerRouteRoute: typeof CareerRouteRouteWithChildren
  SystemsRouteRoute: typeof SystemsRouteRouteWithChildren
  AboutPegasusRoute: typeof AboutPegasusRoute
  BlogRoute: typeof BlogRoute
  ContactRoute: typeof ContactRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about-pegasus': {
      id: '/about-pegasus'
      path: '/about-pegasus'
      fullPath: '/about-pegasus'
      preLoaderRoute: typeof AboutPegasusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/systems': {
      id: '/systems'
      path: '/systems'
      fullPath: '/systems'
      preLoaderRoute: typeof SystemsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/career': {
      id: '/career'
      path: '/career'
      fullPath: '/career'
      preLoaderRoute: typeof CareerRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/systems/education': {
      id: '/systems/education'
      path: '/education'
      fullPath: '/systems/education'
      preLoaderRoute: typeof SystemsEducationRouteImport
      parentRoute: typeof SystemsRouteRoute
    }
    '/systems/bpla': {
      id: '/systems/bpla'
      path: '/bpla'
      fullPath: '/systems/bpla'
      preLoaderRoute: typeof SystemsBplaRouteImport
      parentRoute: typeof SystemsRouteRoute
    }
    '/systems/bpak': {
      id: '/systems/bpak'
      path: '/bpak'
      fullPath: '/systems/bpak'
      preLoaderRoute: typeof SystemsBpakRouteImport
      parentRoute: typeof SystemsRouteRoute
    }
    '/career/$careerId': {
      id: '/career/$careerId'
      path: '/$careerId'
      fullPath: '/career/$careerId'
      preLoaderRoute: typeof CareerCareerIdRouteRouteImport
      parentRoute: typeof CareerRouteRoute
    }
  }
}

interface CareerRouteRouteChildren {
  CareerCareerIdRouteRoute: typeof CareerCareerIdRouteRoute
}

const CareerRouteRouteChildren: CareerRouteRouteChildren = {
  CareerCareerIdRouteRoute: CareerCareerIdRouteRoute,
}

const CareerRouteRouteWithChildren = CareerRouteRoute._addFileChildren(
  CareerRouteRouteChildren,
)

interface SystemsRouteRouteChildren {
  SystemsBpakRoute: typeof SystemsBpakRoute
  SystemsBplaRoute: typeof SystemsBplaRoute
  SystemsEducationRoute: typeof SystemsEducationRoute
}

const SystemsRouteRouteChildren: SystemsRouteRouteChildren = {
  SystemsBpakRoute: SystemsBpakRoute,
  SystemsBplaRoute: SystemsBplaRoute,
  SystemsEducationRoute: SystemsEducationRoute,
}

const SystemsRouteRouteWithChildren = SystemsRouteRoute._addFileChildren(
  SystemsRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CareerRouteRoute: CareerRouteRouteWithChildren,
  SystemsRouteRoute: SystemsRouteRouteWithChildren,
  AboutPegasusRoute: AboutPegasusRoute,
  BlogRoute: BlogRoute,
  ContactRoute: ContactRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
